// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Week13Store.Models
{
    public partial class Customer
    {
        public Customer()
        {
            Orders = new HashSet<Order>();
            OrdersPayments = new HashSet<OrdersPayment>();
            Payments = new HashSet<Payment>();
        }

        public int CustomerId { get; set; }
        public string CustFirstName { get; set; }
        public string CustLastName { get; set; }
        public string CustPhone { get; set; }
        public string CustEmail { get; set; }
        public string CustStreet { get; set; }
        public string CustCity { get; set; }
        public string CustState { get; set; }
        public string CustZip { get; set; }

        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<OrdersPayment> OrdersPayments { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}